from __future__ import annotations

from enum import StrEnum


class SafeErrorCode(StrEnum):
    """Registered redacted errors for the Core's public failure boundary."""

    CONFIGURATION_INVALID = "CORE_CONFIGURATION_INVALID"
    STATE_CORRUPT = "CORE_STATE_CORRUPT"
    STATE_INITIALIZATION_FAILED = "CORE_STATE_INITIALIZATION_FAILED"
    STATE_RELEASE_MISMATCH = "CORE_STATE_RELEASE_MISMATCH"
    DEMO_WORKSPACE_UNAVAILABLE = "DEMO_WORKSPACE_UNAVAILABLE"
    DEMO_WORKSPACE_CAPACITY_EXCEEDED = "DEMO_WORKSPACE_CAPACITY_EXCEEDED"
    DEMO_WORKSPACE_MUTATION_LIMIT_REACHED = "DEMO_WORKSPACE_MUTATION_LIMIT_REACHED"
    DEMO_WORKSPACE_RATE_LIMITED = "DEMO_WORKSPACE_RATE_LIMITED"
    DEMO_WORKSPACE_FRESH_BUNDLE_LIMIT_REACHED = (
        "DEMO_WORKSPACE_FRESH_BUNDLE_LIMIT_REACHED"
    )
    DEMO_WORKSPACE_IDEMPOTENCY_CONFLICT = "DEMO_WORKSPACE_IDEMPOTENCY_CONFLICT"
    DEMO_WORKSPACE_RESOURCE_UNAVAILABLE = "DEMO_WORKSPACE_RESOURCE_UNAVAILABLE"
    DEMO_WORKSPACE_OPERATION_LIMIT_REACHED = "DEMO_WORKSPACE_OPERATION_LIMIT_REACHED"
    OPERATION_QUEUE_CAPACITY_REACHED = "OPERATION_QUEUE_CAPACITY_REACHED"
    OPERATION_MEMORY_HEADROOM_INSUFFICIENT = (
        "OPERATION_MEMORY_HEADROOM_INSUFFICIENT"
    )
    OPERATION_DISK_SPACE_BLOCKED = "OPERATION_DISK_SPACE_BLOCKED"
    OPERATION_NOT_RETRYABLE = "OPERATION_NOT_RETRYABLE"
    CORE_STOPPING = "CORE_STOPPING"
    LIFECYCLE_STOP_UNAVAILABLE = "LIFECYCLE_STOP_UNAVAILABLE"
    INGESTION_IDEMPOTENCY_CONFLICT = "INGESTION_IDEMPOTENCY_CONFLICT"
    DATASET_VERSION_UNAVAILABLE = "DATASET_VERSION_UNAVAILABLE"
    INGESTION_REJECTED = "INGESTION_REJECTED"
    RISK_SIGNAL_SCHEMA_UNSUPPORTED = "RISK_SIGNAL_SCHEMA_UNSUPPORTED"
    RISK_SIGNAL_INTEGRITY_FAILED = "RISK_SIGNAL_INTEGRITY_FAILED"
    RISK_SIGNAL_REVISION_CONFLICT = "RISK_SIGNAL_REVISION_CONFLICT"
    RISK_SIGNAL_CLOCK_UNUSABLE = "RISK_SIGNAL_CLOCK_UNUSABLE"
    REFRESH_CUTOFF_NOT_LATER = "REFRESH_CUTOFF_NOT_LATER"
    RISK_SIGNAL_SUBJECT_UNRESOLVED = "RISK_SIGNAL_SUBJECT_UNRESOLVED"
    RISK_SIGNAL_SUBJECT_AMBIGUOUS = "RISK_SIGNAL_SUBJECT_AMBIGUOUS"
    RISK_SIGNAL_SUBJECT_NOT_OPEN = "RISK_SIGNAL_SUBJECT_NOT_OPEN"
    LOAD_SNAPSHOT_UNRESOLVABLE = "LOAD_SNAPSHOT_UNRESOLVABLE"
    COMMITMENT_CUTOFF_UNUSABLE = "COMMITMENT_CUTOFF_UNUSABLE"
    RISK_SIGNAL_TARGET_MISMATCH = "RISK_SIGNAL_TARGET_MISMATCH"
    RISK_SIGNAL_SCORE_UNUSABLE = "RISK_SIGNAL_SCORE_UNUSABLE"
    RISK_SIGNAL_CONTEXT_CONFLICT = "RISK_SIGNAL_CONTEXT_CONFLICT"
    RISK_SIGNAL_CONTEXT_UNVERIFIABLE = "RISK_SIGNAL_CONTEXT_UNVERIFIABLE"
    RISK_SIGNAL_MODE_MISMATCH = "RISK_SIGNAL_MODE_MISMATCH"
    CAUSAL_QUESTION_VERSION_UNAVAILABLE = "CAUSAL_QUESTION_VERSION_UNAVAILABLE"
    ENGINE_CONFIGURATION_UNAVAILABLE = "ENGINE_CONFIGURATION_UNAVAILABLE"
    SLIPPAGE_DURATION_BASIS_MIXED = "SLIPPAGE_DURATION_BASIS_MIXED"
    PREDICTOR_ARTIFACT_UNAVAILABLE = "PREDICTOR_ARTIFACT_UNAVAILABLE"
    PREDICTIVE_ATTRIBUTION_UNAVAILABLE = "PREDICTIVE_ATTRIBUTION_UNAVAILABLE"
    PROACTIVE_SCHEMA_UNSUPPORTED = "PROACTIVE_SCHEMA_UNSUPPORTED"
    FROZEN_PROMISE_UNAVAILABLE = "FROZEN_PROMISE_UNAVAILABLE"
    FROZEN_PROMISE_CONFLICT = "FROZEN_PROMISE_CONFLICT"
    FROZEN_PROMISE_TEMPORALLY_INVALID = "FROZEN_PROMISE_TEMPORALLY_INVALID"
    ENGINE_INPUT_SCHEMA_UNSUPPORTED = "ENGINE_INPUT_SCHEMA_UNSUPPORTED"
    ENGINE_INPUT_INTEGRITY_MISMATCH = "ENGINE_INPUT_INTEGRITY_MISMATCH"
    ENGINE_FEATURE_CONTRACT_VIOLATION = "ENGINE_FEATURE_CONTRACT_VIOLATION"
    ENGINE_RUNTIME_INCOMPATIBLE = "ENGINE_RUNTIME_INCOMPATIBLE"
    RUN_REPRODUCTION_TARGET_UNAVAILABLE = "RUN_REPRODUCTION_TARGET_UNAVAILABLE"
    RUN_REPRODUCIBILITY_VIOLATION = "RUN_REPRODUCIBILITY_VIOLATION"
    INVESTIGATION_REQUEST_UNAVAILABLE = "INVESTIGATION_REQUEST_UNAVAILABLE"
    DECISION_SUPPORT_HEAD_RACE = "DECISION_SUPPORT_HEAD_RACE"
    DECISION_SUPPORT_EVALUATION_CONFLICT = "DECISION_SUPPORT_EVALUATION_CONFLICT"
    DECISION_SUPPORT_EVALUATION_UNAVAILABLE = "DECISION_SUPPORT_EVALUATION_UNAVAILABLE"
    DECISION_SUPPORT_SERIES_UNAVAILABLE = "DECISION_SUPPORT_SERIES_UNAVAILABLE"
    DRAFT_IDEMPOTENCY_CONFLICT = "DRAFT_IDEMPOTENCY_CONFLICT"
    DRAFT_HEAD_RACE = "DRAFT_HEAD_RACE"
    DRAFT_UNAVAILABLE = "DRAFT_UNAVAILABLE"
    MANAGER_DECISION_IDEMPOTENCY_CONFLICT = "MANAGER_DECISION_IDEMPOTENCY_CONFLICT"
    MANAGER_DECISION_HEAD_RACE = "MANAGER_DECISION_HEAD_RACE"
    MANAGER_DECISION_UNAVAILABLE = "MANAGER_DECISION_UNAVAILABLE"


REGISTERED_SAFE_ERROR_CODES = frozenset(code.value for code in SafeErrorCode)


class CoreSafeError(RuntimeError):
    """A fail-closed error whose public representation contains no internals."""

    def __init__(self, code: SafeErrorCode, recovery_action: str) -> None:
        self.code = code
        self.recovery_action = recovery_action
        super().__init__(code.value)


class WorkspaceRequestError(RuntimeError):
    """A safe, redacted failure while resolving or mutating a Demo Workspace."""

    def __init__(
        self,
        code: SafeErrorCode,
        recovery_action: str,
        status_code: int,
    ) -> None:
        self.code = code
        self.recovery_action = recovery_action
        self.status_code = status_code
        super().__init__(code.value)
